### ISSUE TITLE
로컬 환경에서 도커를 이용하여 루미오를 설치한다.

### ISSUE THREAD

**Issue by phi4grv** [parti-xyz/loomio#1]

**Comment by mozodev** [comment]
문서로 정리해보겠습니다. ㅎ
https://parti-xyz.hackpad.com/Loomio-docker-installation-MVrG6HhSZp1

**Comment by phi4grv** [comment]
http://canoe.parti.xyz/app/discussions/49
도커를 이용하지 않기로 결정해서 이슈를 종료합니다.
