### ISSUE TITLE
엔진야드 도커 관련 자료를 모은다.

### ISSUE THREAD

**Issue by phi4grv** [parti-xyz/loomio#3]
핵패드에 써볼까요? https://parti-xyz.hackpad.com/loomio-deploy#loomio-deploy

**Comment by dalikim** [comment]
모으는 것 좋습니다. 이미 있는 엔진야드 핵패드 페이지에 링크 걸어주세요.

**Comment by phi4grv** [comment]
일단 루미오 배포 마일스톤용 핵패드를 쓰다가 어느정도 정리되면 엔진야드쪽으로 옮기면 어떨까요?

**Comment by dalikim** [comment]
옮기지말고 링크 걸리면 합니다. 한 문서가 길면 보기 힘들어서요.

**Comment by phi4grv** [comment]
링크를 어떻게 거는지 모르겠어요.

**Comment by phi4grv** [comment]
http://canoe.parti.xyz/app/discussions/49
도커를 이용하지 않기로 결정해서 이슈를 종료합니다.

추가적인 정보는 핵패드를 이용합니다.
https://parti-xyz.hackpad.com/Docker-with-Engine-yard-4913CFejrlR
