### ISSUE TITLE
루미오 한국어 번역 나이트빌드 구축

### ISSUE THREAD

**Issue by mozodev** [parti-xyz/loomio#4]
빠띠 계정으로 만든 아마존 aws 프리티어 서버에 구축합니다.
제가 오늘 4시 세션을 열겠습니다.

문서
https://better-democracy.hackpad.com/--N3J850wsakW
- [x] 계정 정보 공유 및 접근
- [x] upstream 최신 소스 반영, vagrant, shell script push
- [x] 서버 프로비저닝
- [x] 프로젝트 빌드
- [x] 웹서버 설정
- [ ] cron 작업 추가
- [x] 도메인 연결?

**Comment by mozodev** [comment]
@parti-xyz/owners 일단 @phi4grv 님과 함께 진행했고 여러가지 삽질들로  방금 끝났습니다.

프리티어 인스턴스 올려서 서버 프로비저닝과 프로젝트 빌드까지 잘 됐고 로컬에서는 잘 띠웠습니다.
라인맨이 localhost로 도메인을 찍고 돌고 있어서 이걸 찾아서 수정하고 웹서버 문제해결하면 일단 빛을 볼 수 있을 것 같습니다.

나이트빌딩을 위해 한국어 파일 새벽 3시에 다운로드 받아서 json으로 바꿔주고 필요하면 웹서버 재시작하는 스크립트를 써서 크론에 등록해놓으면 완료가 되겠습니다~

**Comment by mozodev** [comment]
https://github.com/parti-xyz/loomio/commit/45dfb6b95ea8020035e6cca3f3bd5c356f78b5e3 여기서 쉘 스크립트 확인하실 수 있습니다. 그런데 vagrant에서 작업을 해서 후반부에는 경로가 잘못되서 실패해서 직접 명령어 날려가며 마무리했습니다. .node-version 도 잘못됐네요.. 5.4.0인데.... 수정하겠습니다~

**Comment by mozodev** [comment]
음 삽질을 해본 결과 개발용으로 올려서는 이상한 링크를 클릭하고 프로필에서 언어 설정하는 걸 반복해야하는 문제가 있고 사실 좀 더 생각해보니 현재 루미오오알지도 번역이 반영되어 있는데 권한 문제로 마음껏 이런 저런 화면을 볼 수 없는게 문제인거 같습니다. 그래서 더더욱 완전체 루미오가 필요한 것 같은데 이게 점점 배보다 배꼽이 커지는 양상으로... 점점 새로운 국면으로 넘어가고 있는 거 같네요...

**Comment by dalikim** [comment]
https://www.orchardup.com/ 이런 서비스를 이용하여 도커로 띄우면 어떨까요?

**Comment by dalikim** [comment]
요 이슈는 닫고 다른 이슈로 열어야 겠네요.
